const GITHUB_AUTH_TOKEN = ""
const BOT_NUMBER = "94750625375"
const SESSION_ID = "PRABATH-MD~tdpDlYjY#LGtFmm_AmIYqmPHdQ4LzV_0Awr7l7iVrHKkioKxuNpw"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
